#FROM alpine:latest

#FROM ubuntu:16.04

# Debian
FROM cyberdojofoundation/gcc_assert

LABEL maintainer=jon@jaggersoft.com

RUN echo 'demo with context' > demo.txt
COPY image_name.json .
RUN cat image_name.json
